name: Pull request

on:
  pull_request:
    # we'll also run this when pull requests to develop are opened
    branches: [ develop, test/*, feature/*, docs/*, bug/*, task/* , improvement/*, "master", "main"]
jobs:

   build:
  
    # The type of runner that the job will run on
    runs-on: windows-latest 
    env:
      SOLNAME: AddinGeneratorTesting
      SOLSLN: AddinGeneratorTesting.sln
      SOLDLL: AddinGeneratorTesting.dll
      INNOSETUP_FILE_PATH: Installer.InnoSetup\InstallScript.iss
      SETUP_EXE_PATH: Installer.InnoSetup\Installer\AddinGeneratorTesting.exe
    outputs:
      Version: ${{ steps.gitversion.outputs.nuGetVersionV2 }} 
      CommitsSinceVersionSource: ${{ steps.gitversion.outputs.CommitsSinceVersionSource }}   
     
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    # Installing the MSBuild
    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1.1
    
    # Install and restore the necessary NuGet packages
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.6
     
    - name: Restore NuGet Packages
      run: nuget restore ${{ env.SOLSLN }}
      
    # Change the version inside of the 'InstallScript.iss' file
    - name: Setting new version to the 'InstallScript.iss' file
      run: (Get-Content ${{ env.INNOSETUP_FILE_PATH }}) -replace 'AppVersion=1.0.0', 'AppVersion=v${{ steps.gitversion.outputs.majorMinorPatch }}' | Out-File -encoding ASCII ${{ env.INNOSETUP_FILE_PATH }} 
        
    # Build the solution on the Release mode
    - name: Build and Publish App
      run: msbuild ${{ env.SOLSLN }} /t:Clean,Build /p:platform="Any CPU" /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile      
    
    - name: Sign dlls
      run: |
        $b64      = '${{ secrets.CERTIFICATE }}'
        $filename = 'e-verse.pfx'

        $bytes = [Convert]::FromBase64String($b64)
        [IO.File]::WriteAllBytes($filename, $bytes)

        $dlls = dir -Path .\ -Filter ${{ env.SOLDLL }} -Recurse | %{$_.FullName}
        foreach ($dll in $dlls)
        {
          packages\signtool.10.0.17763.132\tools\signtool.exe sign /f "e-verse.pfx" /p ${{ secrets.CERTIFICATE_PASSWORD }} /t http://timestamp.digicert.com "$dll"
          Write-Host $dll
        }

    - name: Create signed installer
      run: |
        packages\Tools.InnoSetup.6.2.2\tools\ISCC.exe "${{ env.INNOSETUP_FILE_PATH }}"
    - name: Sign installer
      run: |

        packages\signtool.10.0.17763.132\tools\signtool.exe sign /f "e-verse.pfx" /p ${{ secrets.CERTIFICATE_PASSWORD }} /t http://timestamp.digicert.com "${{ env.SETUP_EXE_PATH }}"


    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: installer
        path: "${{ vars.SETUP_EXE_PATH }}*.exe"
        retention-days: 5